### ISSUE TITLE
Click or Tap with 3 Fingers is unavailable

### ISSUE THREAD

**Issue by jo3p** [artginzburg/MiddleClick-Sonoma#94]
### Discussed in https://github.com/artginzburg/MiddleClick-Sonoma/discussions/86

<div type='discussions-op-text'>

<sup>Originally posted by **BenArviv** October 28, 2023</sup>
Dear developer,

I really enjoy the app, but I noticed that that function isn't working. I've downloaded it via Homebrew, and the option for "Tap to click" works perfectly, but I prefer click instead of tap. Is there a way to fix that issue? 

Thank you very much,
Ben</div>

**Comment by snowywol** [comment]
The option for single tap to click is a system setting, nothing to do with MiddleClick. What have you got set in "System Settings" - "Trackpad"? You could post a screenshot to show us and the developer. Like you, I prefer "clicking" instead of "tapping", so see attached screenshot for how my system settings are for the trackpad.
<img width="827" alt="Screenshot 2024-01-06 at 18 38 52" src="https://github.com/artginzburg/MiddleClick-Sonoma/assets/155448666/4fb3bb87-a3c3-4a37-ba4a-e1bdcbeaa680">

It might be more helpful if you could rewrite your "issue" so that it describes what happens WITHOUT MiddleClick installed, what happens WITH MiddleClick installed, and what you EXPECT should happen (but isn't happening) with MiddleClick installed.

**Comment by jo3p** [comment]
~~In my experience the systemwide "Tap to click" option affects one-finger tap/clicks only. Single-finger clicks always work, with this option enabled taps **also** work. I'd like to achieve the same for MiddleClick, where three-finger clicks and taps are both allowed. ~~

When I enable "Tap to click" in MiddleClick (see image below), **only** three-finger taps are recognized, and three-finger clicks are ignored. If I disable the option the behavior is vice versa, with clicks being recognized and taps not being recognized.
<img width="245" alt="image" src="https://github.com/artginzburg/MiddleClick-Sonoma/assets/22777534/16696a50-6fc5-49ac-b114-39541f569477">

What could be causing this issue?~~

**Comment by jo3p** [comment]
NVM, apparently the application behaves as expected, but it's just really bad at recognizing a three-finger click instead of a three-finger tap :)

**Comment by artginzburg** [comment]
This is now fixed in [3.0.0](https://github.com/artginzburg/MiddleClick/releases/tag/3.0.0), thanks!
